language: python
install:
  - sudo apt-get update
  - DEBIAN_FRONTEND=noninteractive sudo apt-get install -y rpm
  - pip install nose pylint
script:
  - ./package-orchestrator.sh
  - pylint --disable=C0103,C0111,C0112 --rcfile=./.pylintrc ./src 
